### ISSUE TITLE
Exception: 'test_run' did not have a 'result' value

### ISSUE THREAD

**Issue by MarceloSalazar** [maclobdell/simple_mbed_test_runner#9]
Launching tests as shown here:
```
python ..\simple_mbed_test_runner\run_all_tests.py
```

Error:

```
+------+--------+-----------+------------+-------------+
| name | target | toolchain | static_ram | total_flash |
+------+--------+-----------+------------+-------------+
+------+--------+-----------+------------+-------------+
Traceback (most recent call last):
  File "C:\mbed\mbed-os-multi\tools\test.py", line 288, in <module>
    status = print_report_exporter.report(build_report)
  File "C:\mbed\mbed-os-multi\tools\test_exporters.py", line 92, in report
    return self.exporter_print(test_summary_ext, print_log_for_failures=print_log_for_failures)
  File "C:\mbed\mbed-os-multi\tools\test_exporters.py", line 345, in exporter_print
    raise Exception("'test_run' did not have a 'result' value")
Exception: 'test_run' did not have a 'result' value
[ERROR] 'test_run' did not have a 'result' value
[mbed] ERROR: "c:\python27\python.exe" returned error.
       Code: 1
       Path: "C:\mbed\mbed-os-multi"
       Command: "c:\python27\python.exe -u C:\mbed\mbed-os-multi\tools\test.py -t iar -m KL82Z --source ..\..
"
       Tip: You could retry the last command with "-v" flag for verbose output
```

Exception raised here: https://github.com/ARMmbed/mbed-os/blob/master/tools/test_exporters.py#L345

I need to investigate how to fix this.

**Comment by MarceloSalazar** [comment]
This seems to be fixed by upgrading to latest commit 7dc0bbbbff7e63e00e6101ae0ac616bea3cba1dd
Thanks!
